# Generated by Django 5.2.17 on 2026-10-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('thumbnail', models.URLField(blank=True, max_length=1000)),
                ('rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
